services:
  db:
    image: postgres:16
    container_name: neuro_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neuro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: neuro_backend
    command: sh -c "./wait-for-db.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/neuro_db
      - INTERNAL_API_KEY=7ceecf26b5afc3684d5e4dfaebed9582e233babd7f637ddcf059cb82b42d746a
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: neuro_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      - INTERNAL_API_URL=http://backend:8000
      - INTERNAL_API_KEY=7ceecf26b5afc3684d5e4dfaebed9582e233babd7f637ddcf059cb82b42d746a
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - AUTH_SECRET=NEXT
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents local node_modules from breaking the container
    depends_on:
      - backend

volumes:
  postgres_data:
