"""add progressive profiling fields

Revision ID: 20330c835f06
Revises: 2f4c2d25f29c
Create Date: 2026-04-02 20:40:28.338453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20330c835f06'
down_revision: Union[str, Sequence[str], None] = '2f4c2d25f29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('user_profiles', sa.Column('archetype_confidence', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('calibration_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'calibration_count')
    op.drop_column('user_profiles', 'archetype_confidence')
    op.create_table('paragraphs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('paragraphs_article_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paragraphs_pkey'))
    )
    op.create_index(op.f('ix_paragraphs_id'), 'paragraphs', ['id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('articles_pkey'))
    )
    op.create_index(op.f('ix_articles_topic'), 'articles', ['topic'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    # ### end Alembic commands ###
